name: Deploy Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "DIR=." >> $GITHUB_ENV

    - name: Start docker containers
      run: |
        docker compose up --wait --wait-timeout 120 --detach

    - name: Show containers
      run: docker container ps

    - name: Networks
      run: docker network ls

    - name: Test
      run: docker exec homarr curl localhost/status

    - name: Test2
      run: curl 0.0.0.0:80
