name: Deploy Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: ubuntu
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install sudo
      run: |
        apt-get update
        apt-get -y install sudo

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install curl -y

    - name: Test curl
      run: curl www.google.com > curl_google_results

    - name: Install docker
      run: curl -fsSL https://get.docker.com/ | sh

    - name: Set env
      run: |
        echo "DIR=." >> $GITHUB_ENV

    - name: Start docker containers
      run: |
        docker compose up --wait --wait-timeout 120 --detach

    - name: Show containers
      run: docker container ps

    - name: Curl localhost
      run: |
        curl 127.0.0.1 > curl_localhost_results
        cat curl_localhost_results

    - name: Is up
      run: |
        curl -sf 127.0.0.1:7575 > /dev/null
        if [ ! $? = 6 ]; then echo "Site is up"; else echo "Site is down"; exit 1; fi
